// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OnlineMuhasebeCodeGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "OnlineMuhasebeCodeGenerator.8c6ca2c1-cd63-4405-a462-68a753002307";
        public const string Name = "OnlineMuhasebeCodeGenerator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Samet Taş";
        public const string Tags = "";
    }
}
