// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OnlineMuhasebeCodeGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string OnlineMuhasebeCodeGeneratorString = "2a4b149d-37fa-4418-99d9-c44706ec168e";
        public static Guid OnlineMuhasebeCodeGenerator = new Guid(OnlineMuhasebeCodeGeneratorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
    }
}